package com.github.abhiram0106.lobotus_assignment.core.util

object Endpoint {
    const val BASE_URL = ""
    const val GET_COMPANIES = ""

    val SAMPLE_RESPONSE = """
        {
    "success": true,
    "message": "Success",
    "errorMessage": "",
    "recordCount": [
        148,
        148,
        10
    ],
    "result": [
        {
            "clientID": 272692,
            "clientName": "AAI SHREE KHODIYAR BEEJ BHANDAR",
            "logo": null,
            "mobile": 9099071603,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": "0",
                "longitude": "0",
                "location": "BORSAD"
            },
            "clientDate": "8/20/2025 2:10:41 PM",
            "flag": "Not Tagged",
            "email": "BRAHM_BHATT@gmail.com",
            "contactPersonName": "BRAHMBHATT",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 633,
            "pincode": "389001",
            "updateCount": 2,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 633,
                "cityName": "Ahmedabad",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272673,
            "clientName": "AGRI BUSINESS CENTER",
            "logo": null,
            "mobile": 9879524674,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "LACHHRAS"
            },
            "clientDate": "8/14/2025 5:02:29 PM",
            "flag": "Not Tagged",
            "email": "MUKESHBHAI_PATEL@gmail.com",
            "contactPersonName": "MUKESHBHAI PATEL",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272726,
            "clientName": "AGRI BUSINESS CENTER - BAVLA",
            "logo": null,
            "mobile": 8824676614,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "BAVLA"
            },
            "clientDate": "8/14/2025 5:02:32 PM",
            "flag": "Not Tagged",
            "email": "AGRIBUSINESSCENTRE@GMAIL.COM",
            "contactPersonName": "SORAMIYA",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272688,
            "clientName": "AGRI BUSINESS CENTER-PETLAD",
            "logo": null,
            "mobile": 9979694055,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "PETLAD"
            },
            "clientDate": "8/14/2025 5:02:30 PM",
            "flag": "Not Tagged",
            "email": "MAKWANA@gmail.com",
            "contactPersonName": "MAKWANA",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272719,
            "clientName": "AGRI BUSINESS CENTRE",
            "logo": null,
            "mobile": 9427041252,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "HALDHARVAS"
            },
            "clientDate": "8/14/2025 5:02:31 PM",
            "flag": "Not Tagged",
            "email": "abchaldharvas@gmail.com",
            "contactPersonName": "JIGNESH KUMAR",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272734,
            "clientName": "AGRI BUSINESS CENTRE - ARAVALLI",
            "logo": null,
            "mobile": 9375102214,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "MODASA"
            },
            "clientDate": "8/14/2025 5:02:25 PM",
            "flag": "Not Tagged",
            "email": "AGRIBUSINESSCENTRE7@GMAIL.COM",
            "contactPersonName": "PATEL",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272680,
            "clientName": "AGRI BUSINESS CENTRE - DHOLKA",
            "logo": null,
            "mobile": 9998374599,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "DHOLKA"
            },
            "clientDate": "8/14/2025 5:02:30 PM",
            "flag": "Not Tagged",
            "email": "PATEL@gmail.com",
            "contactPersonName": "PATEL",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272611,
            "clientName": "AGRI BUSINESS CENTRE - HIRAPUR",
            "logo": null,
            "mobile": 9727704641,
            "addedByUserID": "USR5019",
            "userFullName": "Kalua Ram",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "HIRAPUR"
            },
            "clientDate": "8/14/2025 5:02:25 PM",
            "flag": "Not Tagged",
            "email": "Unknown1@gmail.com",
            "contactPersonName": "Unknown1",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272670,
            "clientName": "AGRI BUSINESS CENTRE - KESHOD",
            "logo": null,
            "mobile": 8980033278,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "KESHOD"
            },
            "clientDate": "8/14/2025 5:02:29 PM",
            "flag": "Not Tagged",
            "email": "Unknown67@gmail.com",
            "contactPersonName": "Unknown67",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        },
        {
            "clientID": 272694,
            "clientName": "AGRI SUPPORT CENTRE",
            "logo": null,
            "mobile": 8849184890,
            "addedByUserID": "USR5015",
            "userFullName": "Admin",
            "enabledStatus": 1,
            "clientLoc": {
                "latitude": null,
                "longitude": null,
                "location": "ASODAR"
            },
            "clientDate": "8/14/2025 5:02:30 PM",
            "flag": "Not Tagged",
            "email": "PANCHAL@gmail.com",
            "contactPersonName": "PANCHAL",
            "landline": "",
            "countryID": 1,
            "zoneID": 1,
            "stateID": 47,
            "cityID": 0,
            "pincode": null,
            "updateCount": 0,
            "retagCount": 0,
            "categoryID": 2067,
            "clientCategoryName": "Client",
            "stageID": 2102,
            "clientStageName": "Mature",
            "city": {
                "cityId": 0,
                "cityName": "NA",
                "stateId": 47,
                "stateName": "Gujarat",
                "countryID": 1,
                "countryName": "India",
                "countryCode": null,
                "zoneId": 1,
                "zoneName": "West"
            },
            "categoryReportingClientIds": null,
            "customerIds": null
        }
    ],
    "bulkUpdateResult": null
}
    """.trimIndent()
}